import pandas as pd
import re
import os
from .read import read



class fetch:
    def reslist_resnum(node_local_pdb, linker_pdb, cut_lib_pdb,a,b,c,linker_order):
        reslist, res_num = [], []
        a,b,c =int(a),int(b),int(c)
        file1 = read.pdb(node_local_pdb)
        reslist1 = file1["Residue"].unique()
        for i in reslist1:
            reslist.append(i)
        file2 = read.pdb(linker_pdb)
        reslist2 = file2["Residue"].unique()
        for i in reslist2:
            reslist.append(i)
        file3 = read.pdb(cut_lib_pdb)
        reslist3 = file3["Residue"].unique()
        for i in reslist3:
            reslist.append(i)

        for i in range(len(reslist1)):
            res_num.append(int(len(file1[file1["Residue"] == reslist1[i]])/ a))
        for i in range(len(reslist2)):
            res_num.append(int(len(file2[file2["Residue"] == reslist2[i]])/ b))
        for i in range(len(reslist3)):
            res_num.append(int(len(file3[file3["Residue"] == reslist3[i]])/ c))

        file_df = pd.concat([file1, file2, file3], ignore_index=True, join="outer")
        path = os.path.abspath("") + "/" + "Residues/"
        os.makedirs(path, exist_ok=True)

        #just for linker  or node or cut or all
        if linker_order ==1:
            exportreslist = reslist1
        if linker_order ==2:
            exportreslist = reslist2
        if linker_order ==3:
            exportreslist = reslist3
        if linker_order ==0:
            exportreslist = reslist

        for i in range(len(exportreslist)):
            with open(path + str(exportreslist[i]) + ".xyz", "w") as f:
                xyz =[]
                xyz.append(str(file_df[file_df["Residue"] == exportreslist[i]].shape[0])+'\n')
                xyz.append('generated by MOF_build\n')
                for index, row in file_df[file_df["Residue"] == exportreslist[i]].iterrows():
                    formatted_line = "%-5s%8.3f%8.3f%8.3f" % (
                        re.sub(r"\d", "", row["Atom_label"]),
                        row["x"],
                        row["y"],
                        row["z"],
                    )
                    xyz.append(formatted_line + "\n")
                f.writelines(xyz)

        

        return reslist, res_num